name = "panchang"
version = "1.0.0"

description = "An iCalendar (RFC 5545) parser library for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "kwando", repo = "panchang" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
splitter = ">= 1.2.0 and < 2.0.0"
tzif = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleamy_bench = ">= 0.6.0 and < 1.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_community_ansi = ">= 1.5.0 and < 2.0.0"
argv = ">= 1.1.0 and < 2.0.0"
global_value = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.6.0 and < 3.0.0"
birdie = ">= 1.0.0 and < 2.0.0"
